### ISSUE TITLE
Cycling Dependencies

### ISSUE THREAD

**Issue by GlitchApotamus** [massivefermion/mungo#2]
As soon as I add the line "import mungo" in my project I get this error.
![Screenshot 2024-03-14 052257](https://github.com/massivefermion/mungo/assets/23411307/2520820d-975f-414e-8240-fb5834c16c9d)
Please fix asap so it's a usable package. I'm using the latest version of the package and Gleam at the moment.

**Comment by massivefermion** [comment]
I can't reproduce this. Could you remove your `build` directory and build the project again?

**Comment by GlitchApotamus** [comment]
> I can't reproduce this. Could you remove your `build` directory and build the project again?

I made a new project instead, it seems to be fixed. Must be a user error. Sorry for confusion

**Comment by GlitchApotamus** [comment]
Does this package support "mongo+srv" connection strings currently? It's not allowing me to connect to my DB in the cloud.

**Comment by massivefermion** [comment]
Clusters and "mongo+srv" connection strings are not supported yet. The only thing you can do is use connection strings like `mongodb://<username>:<password>@<host1>:<port1>,<host2>:<port2>,<host3>:<port3>/<dbName>?authSource=admin` to connect to a replica set, but I haven't done enough due diligence on that either!

**Comment by GlitchApotamus** [comment]
Okay thanks.
